// <auto-generated />
using System;
using Amandaba.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Amandaba.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260907051412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amandaba.Domain.Entities.ConsultaEntity", b =>
                {
                    b.Property<decimal>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdConsulta"));

                    b.Property<string>("Clinica")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_CLINICA_CONSULTA");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_CONSULTA");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CONSULTA_PET");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_RETORNO_CONSULTA");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DIAGNOSTICO_CONSULTA");

                    b.Property<string>("Horario")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("DS_HORARIO_CONSULTA");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_CONSULTA");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MOTIVO_CONSULTA");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO_CONSULTA");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("VL_PESO_CONSULTA");

                    b.Property<string>("Retorno")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("FL_RETORNO_CONSULTA");

                    b.Property<string>("Sintomas")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_SINTOMAS_CONSULTA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_CONSULTA");

                    b.Property<string>("Tratamento")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TRATAMENTO_CONSULTA");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_VETERINARIO_CONSULTA");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_CONSULTA", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.EspecieEntity", b =>
                {
                    b.Property<decimal>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_ESPECIE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdEspecie"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_ESPECIE");

                    b.HasKey("IdEspecie");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TAB_ESPECIE", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.ExameEntity", b =>
                {
                    b.Property<decimal>("IdExame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_EXAME");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdExame"));

                    b.Property<string>("Arquivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_ARQUIVO_EXAME");

                    b.Property<string>("Clinica")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_CLINICA_EXAME");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_EXAME");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REALIZACAO_EXAME");

                    b.Property<DateTime?>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SOLICITACAO_EXAME");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_EXAME");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MOTIVO_EXAME");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_EXAME_PET");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO_EXAME");

                    b.Property<string>("Resultado")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("DS_RESULTADO_EXAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ST_EXAME");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_VETERINARIO_EXAME");

                    b.HasKey("IdExame");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_EXAME", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetAlergiaEntity", b =>
                {
                    b.Property<decimal>("IdRegistroAlergia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_REGISTRO_ALERGIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdRegistroAlergia"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_ALERGIA");

                    b.Property<DateTime?>("DataIdentificacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_IDENTIFICACAO_ALERGIA");

                    b.Property<string>("Gravidade")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_GRAVIDADE_ALERGIA");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_ALERGIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("NM_ALERGIA_PET");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO_ALERGIA");

                    b.Property<string>("Reacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_REACAO_ALERGIA");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TP_ALERGIA_PET");

                    b.HasKey("IdRegistroAlergia");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_PET_ALERGIA", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetDoencaEntity", b =>
                {
                    b.Property<decimal>("IdRegistroDoenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_REGISTRO_DOENCA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdRegistroDoenca"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_DOENCA");

                    b.Property<DateTime?>("DataDiagnostico")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DIAGNOSTICO_DOENCA");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_DOENCA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("NM_DOENCA_PET");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO_DOENCA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_DOENCA_PET");

                    b.Property<string>("Tratamento")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_TRATAMENTO_DOENCA");

                    b.HasKey("IdRegistroDoenca");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_PET_DOENCA", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetEntity", b =>
                {
                    b.Property<decimal>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdPet"));

                    b.Property<string>("Castrado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("FL_CASTRADO_PET");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_COR_PET");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_PET");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO_PET");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_FOTO_PET");

                    b.Property<decimal>("IdEspecie")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_ESPECIE_PET");

                    b.Property<decimal>("IdTutor")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_TUTOR_PET");

                    b.Property<string>("Microchip")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NR_MICROCHIP_PET");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PET");

                    b.Property<string>("Raca")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_RACA_PET");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TP_SEXO_PET");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_PET");

                    b.HasKey("IdPet");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdTutor");

                    b.ToTable("TAB_PET", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetMedicamentoEntity", b =>
                {
                    b.Property<decimal>("IdRegistroMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_REGISTRO_MEDICAMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdRegistroMedicamento"));

                    b.Property<string>("Administracao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_ADMINISTRACAO_MEDICAMENTO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_MEDICAMENTO");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO_MEDICAMENTO");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_TERMINO_MEDICAMENTO");

                    b.Property<decimal?>("Dosagem")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VL_DOSAGEM_MEDICAMENTO");

                    b.Property<string>("Frequencia")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_FREQUENCIA_MEDICAMENTO");

                    b.Property<string>("Horario")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_HORARIO_MEDICAMENTO");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_MEDICAMENTO");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MOTIVO_MEDICAMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("NM_MEDICAMENTO_PET");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO_MEDICAMENTO");

                    b.Property<string>("Prescricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_PRESCRICAO_MEDICAMENTO");

                    b.Property<string>("Quantidade")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("QT_MEDICAMENTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_MEDICAMENTO_PET");

                    b.Property<string>("Unidade")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TP_UNIDADE_MEDICAMENTO");

                    b.HasKey("IdRegistroMedicamento");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_PET_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetPesoEntity", b =>
                {
                    b.Property<decimal>("IdHistoricoPeso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_HISTORICO_PESO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdHistoricoPeso"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_PESO");

                    b.Property<DateTime>("DataMedicao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_MEDICAO_PESO");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_PESO");

                    b.Property<decimal>("Peso")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("VL_PESO_PET");

                    b.HasKey("IdHistoricoPeso");

                    b.HasIndex("IdPet");

                    b.ToTable("TAB_PET_PESO", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetVacinaEntity", b =>
                {
                    b.Property<decimal>("IdAplicacaoVacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_APLICACAO_VACINA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdAplicacaoVacina"));

                    b.Property<string>("Clinica")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_CLINICA_VACINA");

                    b.Property<string>("Comprovante")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_COMPROVANTE_VACINA");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_APLICACAO_VACINA");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_APLICACAO");

                    b.Property<decimal>("IdPet")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_PET_VACINA");

                    b.Property<decimal>("IdVacina")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_VACINA_APLICADA");

                    b.Property<decimal?>("NumeroDose")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_DOSE_VACINA");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NR_LOTE_VACINA");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO_VACINA");

                    b.Property<DateTime?>("ProximaDose")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROXIMA_DOSE_VACINA");

                    b.HasKey("IdAplicacaoVacina");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdVacina");

                    b.ToTable("TAB_PET_VACINA", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.TutorEntity", b =>
                {
                    b.Property<decimal>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_TUTOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdTutor"));

                    b.Property<decimal>("IdUsuario")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_USUARIO_TUTOR");

                    b.HasKey("IdTutor");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("TAB_TUTOR", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<decimal>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdUsuario"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF_USUARIO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO_USUARIO");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO_USUARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_SENHA_HASH_USUARIO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_USUARIO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE_USUARIO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TAB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.VacinaEntity", b =>
                {
                    b.Property<decimal>("IdVacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID_VACINA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdVacina"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_VACINA");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_FABRICANTE_VACINA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_VACINA");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TP_VACINA");

                    b.HasKey("IdVacina");

                    b.ToTable("TAB_VACINA", (string)null);
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.ConsultaEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.ExameEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Exames")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetAlergiaEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Alergias")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetDoencaEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Doencas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.EspecieEntity", "Especie")
                        .WithMany("Pets")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amandaba.Domain.Entities.TutorEntity", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetMedicamentoEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Medicamentos")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetPesoEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Pesos")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetVacinaEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.PetEntity", "Pet")
                        .WithMany("Vacinas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amandaba.Domain.Entities.VacinaEntity", "Vacina")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("IdVacina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.TutorEntity", b =>
                {
                    b.HasOne("Amandaba.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithOne("Tutor")
                        .HasForeignKey("Amandaba.Domain.Entities.TutorEntity", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.EspecieEntity", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.PetEntity", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Consultas");

                    b.Navigation("Doencas");

                    b.Navigation("Exames");

                    b.Navigation("Medicamentos");

                    b.Navigation("Pesos");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.TutorEntity", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Amandaba.Domain.Entities.VacinaEntity", b =>
                {
                    b.Navigation("Aplicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
