name: Deploy Amandaba to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-amandaba-${{ secrets.RM_AZURE }}
  WEBAPP_NAME: webapp-amandaba-${{ secrets.RM_AZURE }}
  PROJECT_PATH: ./Amandaba.API/Amandaba.API.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish (Corrigido com o PROJECT_PATH)
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish

      - name: Zipar os arquivos para Deploy
        run: |
          cd publish
          zip -r ../app.zip .

      - name: Login na Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar Connection String do Oracle no App Service
        run: |
          az webapp config appsettings set \
            --resource-group "$RESOURCE_GROUP" \
            --name "$WEBAPP_NAME" \
            --settings \
              ConnectionStrings__Oracle="User Id=${{ secrets.ORACLE_USER }};Password=${{ secrets.ORACLE_PASSWORD }};Data Source=oracle.fiap.com.br:1521/ORCL;"

      - name: Deploy no Azure Web App
        run: |
          az webapp deploy \
            --resource-group "$RESOURCE_GROUP" \
            --name "$WEBAPP_NAME" \
            --src-path app.zip \
            --type zip

      - name: Logout da Azure
        run: az logout
        if: always()